name: deploy-rocketseat-vpc

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment name'
        required: true
        default: 'dev'
      ENV_VERSION:
        description: 'Environment verion'
        required: true
        default: 'v1'

jobs:
  deploy:
    env:
      PROJECT_NAME: iac-network
      AWS_REGION: us-east-1
      REMOTE_STATE_BUCKET: rocketseat-remote-state
      REMOTE_STATE_FILE: rocketseat-vpc.tfstate
      REMOTE_STATE_AWS_REGION: us-east-1
      PRODUCT: network
      CREATED_BY: devops-tools
      OWNER: squad-network
      ENV: ${{ github.event.inputs.ENV }}
      ENV_VERSION: ${{ github.event.inputs.ENV_VERSION }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure-crentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_NETWORK_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_NETWORK_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: deploy
      run: chmod +x ./devops/scripts/unit-test.sh && ./devops/scripts/unit-test.sh